### ISSUE TITLE
Error in curl::curl_fetch_disk() when using store_bikedata()

### ISSUE THREAD

**Issue by philstraforelli** [ropensci/bikedata#49]
I'm looking to learn more about the bikedata package, and I was going through this vignette: https://ropensci.github.io/bikedata/

However, when I attempt the following: `store_bikedata (city = 'nyc', bikedb = 'bikedb', dates = 201601:201603)`, I get the following error: 

> Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Failed to open file C:\Users\PSTRAFC:\Users\PStraforelli\Documents1\AppData\Local\Temp\RtmpwZUPl6\201601-citibike-tripdata.zip.

I understand that this error may be unrelated to the bikedata package, but I was hoping I could at least get some pointers on how I could debug this. I haven't been able to find anything via google.

**Comment by mpadge** [comment]
I'm pretty sure that's been solved in the latest version which was released last week. Could you please try,
```
update.packages("bikedata")
```
Then load as usual, re-run your code, and let me know if that solves it. This error was due to citibike publishing zip files which had no content, which most zip libraries don't know how to deal with.

**Comment by philstraforelli** [comment]
The error is still occurring after installing the development version. I've also tried the following from [here](https://cran.r-project.org/web/packages/bikedata/vignettes/bikedata.html#2_main_functions) and got the same error.

Here's my session Info, if it helps:

```
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bikedata_0.1.0

loaded via a namespace (and not attached):
 [1] igraph_1.1.2     Rcpp_0.12.14     osmdata_0.0.5    xml2_1.1.1       knitr_1.17       magrittr_1.5    
 [7] devtools_1.13.4  rvest_0.3.2      bit_1.1-12       lattice_0.20-35  R6_2.2.2         rlang_0.1.4     
[13] plyr_1.8.4       stringr_1.2.0    blob_1.1.0       httr_1.3.1       tools_3.4.2      grid_3.4.2      
[19] DBI_0.7          dodgr_0.0.3      git2r_0.19.0     withr_2.1.0      rbenchmark_1.0.0 yaml_2.1.14     
[25] bit64_0.9-7      digest_0.6.12    tibble_1.3.4     reshape2_1.4.2   curl_3.0         memoise_1.1.0   
[31] RSQLite_2.0      sp_1.2-5         stringi_1.1.6    compiler_3.4.2   lubridate_1.7.1  jsonlite_1.5    
[37] pkgconfig_2.0.1 
```

**Comment by mpadge** [comment]
I can't reproduce the error. Based on your error output above, my best guess would be that it's a windows write permission issue. Specifically, you likely do not have permissions on your system to write (within **R**) to `tempdir()`. What if you try using a local directory? (even just `getwd()` instead of `tempdir()`)

**Comment by philstraforelli** [comment]
Yeah, in fact I was initially using my project directory, and still getting that error. I tried on my personal Windows machine (Windows 10 in that case) and got the same issue. A colleague of mine uses a Mac. I'll ask him if this works on his end, and will report back. We also have a R studio Linux server running, so I'll try it there as well.
